using System.Globalization;

namespace RikkaHub.App.Services;

/// <summary>
/// Localization — port of the Android app's strings.xml resources (en / zh).
/// Follows the OS language unless overridden in settings.
/// </summary>
public static class Loc
{
    public static string Language { get; private set; } = "en"; // resolved language

    private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["en"] = new Dictionary<string, string>
        {
            ["app_name"] = "RikkaHub",
            ["chat"] = "Chat",
            ["new_chat"] = "New Chat",
            ["history"] = "History",
            ["settings"] = "Settings",
            ["search_conversations"] = "Search conversations",
            ["input_placeholder"] = "Message Rikka…",
            ["send"] = "Send",
            ["stop"] = "Stop",
            ["copy"] = "Copy",
            ["copied"] = "Copied",
            ["regenerate"] = "Regenerate",
            ["edit"] = "Edit",
            ["delete"] = "Delete",
            ["rename"] = "Rename",
            ["cancel"] = "Cancel",
            ["confirm"] = "Confirm",
            ["save"] = "Save",
            ["providers"] = "Providers",
            ["provider"] = "Provider",
            ["add_provider"] = "Add Provider",
            ["edit_provider"] = "Edit Provider",
            ["api_key"] = "API Key",
            ["base_url"] = "Base URL",
            ["fetch_models"] = "Fetch Models",
            ["fetching_models"] = "Fetching models…",
            ["fetch_models_ok"] = "Fetched {0} models",
            ["fetch_models_fail"] = "Failed to fetch models",
            ["models"] = "Models",
            ["add_model"] = "Add Model",
            ["model_id"] = "Model ID",
            ["model_name"] = "Display Name",
            ["model_display"] = "Model Display",
            ["delete_provider_confirm"] = "Delete this provider and all its models?",
            ["delete_model_confirm"] = "Delete this model?",
            ["enabled"] = "Enabled",
            ["theme"] = "Theme",
            ["dark_mode"] = "Dark Mode",
            ["dark_mode_auto"] = "Follow system",
            ["dark_mode_dark"] = "Dark",
            ["dark_mode_light"] = "Light",
            ["dynamic_color"] = "Dynamic Color (Material You)",
            ["seed_color"] = "Seed Color",
            ["about"] = "About",
            ["about_version"] = "Version",
            ["about_source"] = "Source (Android)",
            ["about_port"] = "Windows port repository",
            ["about_desc"] = "A Windows native port of RikkaHub — an LLM chat client that supports multiple providers.",
            ["display"] = "Display",
            ["bubble_style"] = "Bubble style",
            ["bubble_style_bubble"] = "Bubble",
            ["bubble_style_plain"] = "Plain",
            ["show_token_usage"] = "Show token usage",
            ["language"] = "Language",
            ["language_system"] = "Follow system",
            ["assistant"] = "Assistant",
            ["assistants"] = "Assistants",
            ["new_assistant"] = "New Assistant",
            ["assistant_name"] = "Name",
            ["assistant_icon"] = "Icon",
            ["assistant_desc"] = "Description",
            ["system_prompt"] = "System Prompt",
            ["delete_assistant_confirm"] = "Delete this assistant?",
            ["select_model"] = "Select Model",
            ["search_models"] = "Search models",
            ["no_models_hint"] = "No models yet. Go to Settings → Providers to add a provider and models.",
            ["empty_chat_title"] = "How can I help you today?",
            ["no_provider_hint"] = "Configure a provider first",
            ["go_to_settings"] = "Go to Settings",
            ["input_too_long"] = "Input too long",
            ["delete_conversation_confirm"] = "Delete this conversation?",
            ["generate_error"] = "Generation failed",
            ["usage"] = "Usage",
            ["tokens"] = "Tokens",
            ["thinking"] = "Thinking",
            ["thinking_done"] = "Thought for {0}s",
            ["tools"] = "Tools",
            ["clear_conversation"] = "Clear conversation",
            ["export_conversation"] = "Export conversation",
            ["pinned"] = "Pinned",
            ["pin"] = "Pin",
            ["unpin"] = "Unpin",
            ["retry"] = "Retry",
            ["temperature"] = "Temperature",
            ["top_p"] = "Top P",
            ["max_tokens"] = "Max Tokens",
            ["parameters"] = "Parameters",
            ["reset"] = "Reset",
            ["error"] = "Error",
            ["ok"] = "OK",
            ["temperature_placeholder"] = "Default",
            ["image"] = "Image",
            ["send_image"] = "Send image",
            ["attached_images"] = "Attached images",
            ["remove"] = "Remove",
            ["quick_message"] = "Quick Message",
            ["version"] = "1.0.0",
            ["exit"] = "Exit",
            ["more"] = "More",
            ["rename_conversation"] = "Rename conversation",
            ["title"] = "Title",
            ["conversations"] = "Conversations",
            ["no_conversations"] = "No conversations yet",
            ["provider_type"] = "Provider Type",
            ["provider_name"] = "Provider Name",
            ["chat_model"] = "Chat Model",
            ["fast_model"] = "Fast Model",
            ["other_settings"] = "Other",
        },
        ["zh"] = new Dictionary<string, string>
        {
            ["app_name"] = "RikkaHub",
            ["chat"] = "聊天",
            ["new_chat"] = "新建聊天",
            ["history"] = "历史",
            ["settings"] = "设置",
            ["search_conversations"] = "搜索对话",
            ["input_placeholder"] = "给 Rikka 发送消息…",
            ["send"] = "发送",
            ["stop"] = "停止",
            ["copy"] = "复制",
            ["copied"] = "已复制",
            ["regenerate"] = "重新生成",
            ["edit"] = "编辑",
            ["delete"] = "删除",
            ["rename"] = "重命名",
            ["cancel"] = "取消",
            ["confirm"] = "确认",
            ["save"] = "保存",
            ["providers"] = "供应商",
            ["provider"] = "供应商",
            ["add_provider"] = "添加供应商",
            ["edit_provider"] = "编辑供应商",
            ["api_key"] = "API 密钥",
            ["base_url"] = "接口地址",
            ["fetch_models"] = "获取模型列表",
            ["fetching_models"] = "正在获取模型…",
            ["fetch_models_ok"] = "已获取 {0} 个模型",
            ["fetch_models_fail"] = "获取模型失败",
            ["models"] = "模型",
            ["add_model"] = "添加模型",
            ["model_id"] = "模型 ID",
            ["model_name"] = "显示名称",
            ["model_display"] = "模型显示",
            ["delete_provider_confirm"] = "删除该供应商及其所有模型？",
            ["delete_model_confirm"] = "删除该模型？",
            ["enabled"] = "启用",
            ["theme"] = "主题",
            ["dark_mode"] = "深色模式",
            ["dark_mode_auto"] = "跟随系统",
            ["dark_mode_dark"] = "深色",
            ["dark_mode_light"] = "浅色",
            ["dynamic_color"] = "动态取色 (Material You)",
            ["seed_color"] = "种子颜色",
            ["about"] = "关于",
            ["about_version"] = "版本",
            ["about_source"] = "原项目 (Android)",
            ["about_port"] = "Windows 移植仓库",
            ["about_desc"] = "RikkaHub 的 Windows 原生移植版 — 支持多供应商的大模型聊天客户端。",
            ["display"] = "显示",
            ["bubble_style"] = "气泡样式",
            ["bubble_style_bubble"] = "气泡",
            ["bubble_style_plain"] = "简洁",
            ["show_token_usage"] = "显示 Token 用量",
            ["language"] = "语言",
            ["language_system"] = "跟随系统",
            ["assistant"] = "助手",
            ["assistants"] = "助手",
            ["new_assistant"] = "新建助手",
            ["assistant_name"] = "名称",
            ["assistant_icon"] = "图标",
            ["assistant_desc"] = "描述",
            ["system_prompt"] = "系统提示词",
            ["delete_assistant_confirm"] = "删除该助手？",
            ["select_model"] = "选择模型",
            ["search_models"] = "搜索模型",
            ["no_models_hint"] = "暂无模型。请前往 设置 → 供应商 添加供应商和模型。",
            ["empty_chat_title"] = "今天我能帮你什么？",
            ["no_provider_hint"] = "请先配置供应商",
            ["go_to_settings"] = "前往设置",
            ["input_too_long"] = "输入过长",
            ["delete_conversation_confirm"] = "删除该对话？",
            ["generate_error"] = "生成失败",
            ["usage"] = "用量",
            ["tokens"] = "Token",
            ["thinking"] = "思考中",
            ["thinking_done"] = "思考了 {0} 秒",
            ["tools"] = "工具",
            ["clear_conversation"] = "清空对话",
            ["export_conversation"] = "导出对话",
            ["pinned"] = "已置顶",
            ["pin"] = "置顶",
            ["unpin"] = "取消置顶",
            ["retry"] = "重试",
            ["temperature"] = "温度",
            ["top_p"] = "Top P",
            ["max_tokens"] = "最大 Token",
            ["parameters"] = "参数",
            ["reset"] = "重置",
            ["error"] = "错误",
            ["ok"] = "好",
            ["temperature_placeholder"] = "默认",
            ["image"] = "图片",
            ["send_image"] = "发送图片",
            ["attached_images"] = "已附加图片",
            ["remove"] = "移除",
            ["quick_message"] = "快捷消息",
            ["version"] = "1.0.0",
            ["exit"] = "退出",
            ["more"] = "更多",
            ["rename_conversation"] = "重命名对话",
            ["title"] = "标题",
            ["conversations"] = "对话",
            ["no_conversations"] = "暂无对话",
            ["provider_type"] = "供应商类型",
            ["provider_name"] = "供应商名称",
            ["chat_model"] = "聊天模型",
            ["fast_model"] = "快速模型",
            ["other_settings"] = "其他",
        },
    };

    public static string Tr(string key, params object?[] args)
    {
        var lang = Language;
        if (!Table.TryGetValue(lang, out var dict))
            dict = Table["en"];
        var s = dict.TryGetValue(key, out var v) ? v : (Table["en"].TryGetValue(key, out var e) ? e : key);
        if (args.Length > 0)
            return string.Format(s, args);
        return s;
    }

    public static void Init(string preference)
    {
        if (preference is "zh" or "en")
        {
            Language = preference;
            return;
        }
        var sysLang = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        if (sysLang.StartsWith("zh", StringComparison.OrdinalIgnoreCase))
        {
            // Simplified / Traditional mapping
            Language = "zh";
        }
        else
        {
            Language = "en";
        }
    }
}
